### ISSUE TITLE
Log not showing

### ISSUE THREAD

**Issue by charleston10** [rapid7/r7insight_node#32] opened 2021-08-03 14:36 UTC
I created a test application to validate the tool

I followed the Quick Add tutorial and it wasn't working at all, using the same code passed as an example

The generated token is invalid, after a while trying I went to the LogName settings by clicking Edit Settings and I saw that it has two tokens Log token & Log Key

And I compared the Log Token with what was created when I started the project and they were different
I used the Log Token that appeared in Edit Settings and that's how it worked

Until I found out it took a while and it was really boring, but in the end everything worked out.

I'm leaving feedback here as there may be issues with new people

**Comment by sbialkowski-r7** [comment] 2021-08-04 08:54
Hey @charleston10, thanks for dropping the issue

So just so I'm understanding this correctly, in `Quick Add` in the UI, you selected the Node library and the generated code with the token was incorrect?

And then you went into the log settings themselves and the token was different?

**Comment by AntonioHReyes** [comment] 2021-11-10 20:00
Same issue!!! i'm create a token for nodejs but don't show my log

**Comment by AntonioHReyes** [comment] 2021-11-15 04:41
I found the problem but not the solution, the problem is that my Docker image somehow blocks the sending of logs

**Comment by rjacobs-r7** [comment] 2022-03-07 15:42
This may have been a UI issue that has since been fixed, as this no longer seems to be an issue. Closing this ticket.

**Closed by rjacobs-r7** 2022-03-07 15:42 UTC
